version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SuaSenha123!"
      ACCEPT_EULA: "Y"
    networks:
      - healthnet

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - healthnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - healthnet

  healthmed-api:
    image: luisfernandofernandes/hackathon-healthmed:2.3
    container_name: healthmed
    depends_on:
      - sqlserver
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;User Id=sa;Password=SuaSenha123!;TrustServerCertificate=True;MultipleActiveResultSets=true;"
      ConnectionStrings__Redis: "redis:6379"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: "guest"
      RabbitMQ__Password: "guest"
      RabbitMQ__ExchangeAgendar: "Hackathon.HeathMed.Agendar"
    networks:
      - healthnet

  agendamentos-worker:
    image: luisfernandofernandes/hackathon-agendar-service:2.0
    container_name: agendamentos-worker
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;User Id=sa;Password=SuaSenha123!;TrustServerCertificate=True;MultipleActiveResultSets=true;"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: "guest"
      RabbitMQ__Password: "guest"
      RabbitMQ__Exchange: "Hackathon.HeathMed.Agendar"
      RabbitMQ__QueueName: "Hackathon.HeathMed.Agendar.AddToDatabase"
    networks:
      - healthnet

networks:
  healthnet:
    driver: bridge
