version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SuaSenha123!"
      ACCEPT_EULA: "Y"
    networks:
      - healthnet

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - healthnet

  healthmed-api:
    build:
      context: .
      dockerfile: Hackathon.HealthMed.Api/Dockerfile
    image: hackathon-healthmed:1.0
    container_name: healthmed
    depends_on:
      - sqlserver
      - redis
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;User Id=sa;Password=SuaSenha123!;TrustServerCertificate=True;MultipleActiveResultSets=true;"
      ConnectionStrings__Redis: "redis:6379"
    networks:
      - healthnet

networks:
  healthnet:
    driver: bridge