apiVersion: apps/v1
kind: Deployment
metadata:
  name: agendar-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agendar-service
  template:
    metadata:
      labels:
        app: agendar-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5001"
    spec:
      containers:
      - name: agendar-service
        image: luisfernandofernandes/hackathon-agendar-service:2.3
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver;Database=HealthMedDB;User Id=sa;Password=SuaSenha123!;TrustServerCertificate=True;MultipleActiveResultSets=true;"
        - name: RabbitMQ__HostName
          value: "rabbitmq"
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__UserName
          value: "guest"
        - name: RabbitMQ__Password
          value: "guest"
        - name: RabbitMQ__Exchange
          value: "Hackathon.HeathMed.Agendar"
        - name: RabbitMQ__QueueName
          value: "Hackathon.HeathMed.Agendar.AddToDatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: agendar-service
spec:
  selector:
    app: agendar-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: ClusterIP
